ballot/urls.py
from django.urls import path
from . import views

app_name = 'ballot'
urlpatterns = [
    path('create/', views.create, name='create'),
    path('seal/', views.seal, name='seal'),
]

bbevoting_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('ballot/', include('ballot.urls')),
    path('sim/', include('simulation.urls')),
    path('', include('welcome.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

welcome/urls.py
from django.urls import path
from . import views

app_name = 'welcome'
urlpatterns = [
    path('', views.home, name='home'),
]

ballot/models.py
from django.db import models

ballot/views.py
import time, datetime
import uuid
from Crypto.Signature import DSS
from Crypto.Hash import SHA3_256
from Crypto.PublicKey import ECC
from Crypto import Random
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import redirect, render

def create(request):
    if request.method == 'POST':
        voter_id = request.POST.get('voter-id-input')
        vote = request.POST.get('vote-input')
        private_key = request.POST.get('private-key-input')

        # Create ballot as string vector
        timestamp = datetime.datetime.now().timestamp()
        ballot = "{}|{}|{}".format(voter_id, vote, timestamp)
        print('\ncasted ballot: {}\n'.format(ballot))
        signature = ''
        try:
            # Create signature
            priv_key = ECC.import_key(private_key)
            h = SHA3_256.new(ballot.encode('utf-8'))
            signature = DSS.new(priv_key, 'fips-186-3').sign(h)
            print('\nsignature: {}\n'.format(signature.hex()))

            # Verify the signature using registered public key
            pub_key = ECC.import_key(settings.PUBLIC_KEY)
            verifier = DSS.new(pub_key, 'fips-186-3')
        
            verifier.verify(h, signature)
            status = 'The ballot is signed successfully.'
            error = False
        except (ValueError, TypeError):
            status = 'The key is not registered.'
            error = True
        
        context = {
            'ballot': ballot,
            'signature': signature,
            'status': status,
            'error': error,
        }
        return render(request, 'ballot/status.html', context)

    context = {'voter_id': uuid.uuid4(), }
    return render(request, 'ballot/create.html', context)

def seal(request):
    if request.method == 'POST':
        ballot = request.POST.get('ballot_input')
        ballot_byte = ballot.encode('utf-8')
        ballot_hash = SHA3_256.new(ballot_byte).hexdigest()
        # Puzzle requirement: '0' * n (n leading zeros)
        puzzle, pcount = settings.PUZZLE, settings.PLENGTH
        nonce = 0

        # Try to solve puzzle
        start_time = time.time() # benchmark
        timestamp = datetime.datetime.now().timestamp() # mark the start of mining effort
        while True:
            block_hash = SHA3_256.new(("{}{}{}".format(ballot, nonce, timestamp).encode('utf-8'))).hexdigest()
            print('\ntrial hash: {}\n'.format(block_hash))
            if block_hash[:pcount] == puzzle:
                stop_time = time.time() # benchmark
                print("\nblock is sealed in {} seconds\n".format(stop_time-start_time))
                break
            nonce += 1

        context = {
            'prev_hash': 'GENESIS',
            'transaction_hash': ballot_hash,
            'nonce': nonce,
            'block_hash': block_hash,
            'timestamp': timestamp,
        }
        return render(request, 'ballot/seal.html', context)
    return redirect('ballot:create')

ballot/templates/ballot/create.html
{% extends 'base.html' %}
{% load static %}
{% block title_bl %}Create ballot{% endblock %}
{% block body_bl %}
<div class="container" style="border: 1px solid black; background-color: #F5F5F5;">
    <h1 style="text-align:center;">Best Singer Nomination</h1>
    <form action="{% url 'ballot:create' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="voter-id-input">Your ID:</label>
            <input name="voter-id-input" type="text" class="form-control" id="voter-id-input" placeholder="fe021e59-c29d-4532-9e99-5c42f1910af3" value="{{ voter_id }}" required autofocus>
        </div>
        <div id="candidate" style="padding:20px 0;">
            <p style="text-align:center;">Eligible candidates are shown below:</p>
            <div class="row">
                <div class="col-md-4">
                    <p style="text-align: center;"><img src="{% static 'ballot/img/arjit.jpg' %}"></p>
                    <p style="text-align: center;">Arijit Singh (1)</p>
                </div>
                <div class="col-md-4">
                    <p style="text-align: center;"><img src="{% static 'ballot/img/darshan.jpg' %}"></p>
                    <p style="text-align: center;">Darshan Raval (2)</p>
                </div>
                <div class="col-md-4">
                    <p style="text-align: center;"><img src="{% static 'ballot/img/anuv.jpg' %}"></p>
                    <p style="text-align: center;">Anuv Jain (3)</p>
                </div>
            </div>
        </div>
        <div class="form-group">
                <label for="vote-input">Your candidate choice:</label>
                <input name="vote-input" type="number" class="form-control" id="voter-input" placeholder="Enter valid candidate ID" min="1" max="3" required>
            </div>
        <div class="form-group">
            <label for="private-key-textarea">Your private key:</label>
            <textarea name="private-key-input" class="form-control" id="private-key-textarea" rows="10" required></textarea>
            <small id="privatekeyHelpBlock" class="form-text text-muted">
                The matching public key must already be registered.
            </small>
        </div>
        <button type="submit" class="btn btn-primary btn-block">Submit ballot</button>
    </form>
</div>
{% endblock %}

ballot/templates/ballot/seal.html
{% extends 'base.html' %}
{% load static %}
{% load sim_filters %}
{% block title_bl %}Block detail{% endblock %}

{% block body_bl %}
    <div class="container">
        <h1>Block detail</h1>
        <div style="padding:3%; border: 1px solid black;">
            <dl class="row">
                <dt class="col-sm-3">Previous hash</dt>
                <dd class="col-sm-9">{{ prev_hash }}</dd>
    
                <dt class="col-sm-3">Transaction hash</dt>
                <dd class="col-sm-9"><code>{{ transaction_hash }}</code></dd>
    
                <dt class="col-sm-3">Block hash</dt>
                <dd class="col-sm-9"><code>{{ block_hash }}</code></dd>
    
                <dt class="col-sm-3">Nonce</dt>
                <dd class="col-sm-9">{{ nonce }}</dd>
    
                <dt class="col-sm-3">Timestamp</dt>
                <dd class="col-sm-9">{{ timestamp }} ({{ timestamp|unix_to_date|date:"Y-m-d H:i:s" }})</dd>
            </dl>
            <a class="btn btn-primary btn-small" href="{% url 'welcome:home' %}" role="button">Back to homepage</a>
        </div>
    </div>
{% endblock %}

ballot/templates/ballot/status.html
{% extends 'base.html' %}
{% block title_bl %}Status{% endblock %}

{% block body_bl %}
<div class="container">
    <h1>Signature Verification</h1>
    <div style="padding:3%; border:1px solid black;">
        <p>Your ballot was <code>{{ ballot }}</code></p>
        <p>Generated signature <code>{{ signature }}</code></p><br>
        <p style="color:{% if error %}red{% else %}green{% endif %};">
            {{ status }}
        </p>
    
        {% if not error %}
        <form action="{% url 'ballot:seal' %}" method="POST">
            {% csrf_token %}
            <input name="ballot_input" type="hidden" value="{{ ballot }}">
            <button type="submit" class="btn btn-primary btn-block">Seal the ballot</button>
        </form>
        {% endif %}
    </div>
</div>

{% endblock %}