ballot/urls.py
from django.urls import path
from . import views

app_name = 'ballot'
urlpatterns = [
    path('create/', views.create, name='create'),
    path('seal/', views.seal, name='seal'),
]

bbevoting_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('ballot/', include('ballot.urls')),
    path('sim/', include('simulation.urls')),
    path('', include('welcome.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

simulation/urls.py
from django.urls import path
from . import views

app_name = 'simulation'
urlpatterns = [
    path('generate/', views.generate, name='generate'),
    path('seal/', views.seal, name='seal'),
    path('transactions/', views.transactions, name='transactions'),
    path('blockchain/', views.blockchain, name='blockchain'),

    path('block/<str:block_hash>/', views.block_detail, name='block_detail'),

    path('verify/', views.verify, name='verify'),
    path('sync/', views.sync, name='sync'),
    path('sync_block/<int:block_id>/', views.sync_block, name='sync_block'),
]

welcome/urls.py
from django.urls import path
from . import views

app_name = 'welcome'
urlpatterns = [
    path('', views.home, name='home'),
]

welcome/models.py
from django.db import models

# Create your models here.

welcome/views.py
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    context = {
        'tx': settings.N_TRANSACTIONS,
        'bl': settings.N_BLOCKS,
    }
    return render(request, 'welcome/home.html', context)

welcome/templates/welcome/home.html
{% extends 'base.html' %}
{% load static %}
{% block title_bl %}Home{% endblock %}

{% block body_bl %}
<div class="container">
    <div class="text-center mb-4">
        <h1 style="padding-bottom:5%;">Blockchain-Based E-Voting System</h1>
    </div>
    <div class="row">
        <div class="col-md-5 menu">
            <h2>BLOCK</h2>
            <p>This part will show:</p>
            <ul>
                <li>Example of ballot</li>
                <li>Ballot structure</li>
                <li>Signature verification</li>
                <li>Block sealing process</li>
            </ul>
            <div class="btn-menu">
                <a class="btn btn-outline-primary btn-block btn-menu" href="{% url 'ballot:create' %}" role="button">Start</a>
            </div>
        </div>
        <div class="col-md-5 menu">
            <h2>CHAIN</h2>
            <p>This part will show:</p>
            <ul>
                <li>Batch transactions ({{ tx }})</li>
                <li>Block chaining ({{ bl }})</li>
                <li>Block detail</li>
                <li>Blocks verification</li>
            </ul>
            <div class="btn-menu">
                <a class="btn btn-outline-primary btn-menu" href="{% url 'simulation:generate' %}" role="button">Start</a>
                <a class="btn btn-outline-primary btn-menu" href="{% url 'simulation:transactions' %}" role="button">See transactions</a>
                <a class="btn btn-outline-primary btn-menu" href="{% url 'simulation:blockchain' %}" role="button">See blocks</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}