ballot/urls.py
from django.urls import path
from . import views

app_name = 'ballot'
urlpatterns = [
    path('create/', views.create, name='create'),
    path('seal/', views.seal, name='seal'),
]

bbevoting_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('ballot/', include('ballot.urls')),
    path('sim/', include('simulation.urls')),
    path('', include('welcome.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

simulation/urls.py
from django.urls import path
from . import views

app_name = 'simulation'
urlpatterns = [
    path('generate/', views.generate, name='generate'),
    path('seal/', views.seal, name='seal'),
    path('transactions/', views.transactions, name='transactions'),
    path('blockchain/', views.blockchain, name='blockchain'),

    path('block/<str:block_hash>/', views.block_detail, name='block_detail'),

    path('verify/', views.verify, name='verify'),
    path('sync/', views.sync, name='sync'),
    path('sync_block/<int:block_id>/', views.sync_block, name='sync_block'),
]

welcome/urls.py
from django.urls import path
from . import views

app_name = 'welcome'
urlpatterns = [
    path('', views.home, name='home'),
]

simulation/models.py
import datetime, uuid, random
from django.db import models

def get_vote():
    return random.randint(1, 3)

def get_timestamp():
    return datetime.datetime.now().timestamp()

class Vote(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    vote = models.IntegerField(default=get_vote)
    timestamp = models.FloatField(default=get_timestamp)
    # Not ForeignKey! See transactions() in simulation.views for implications
    block_id = models.IntegerField(null=True)

    def __str__(self):
        return "{}|{}|{}".format(self.id, self.vote, self.timestamp)

class Block(models.Model):
    prev_h = models.CharField(max_length=64, blank=True)
    merkle_h = models.CharField(max_length=64, blank=True)
    h = models.CharField(max_length=64, blank=True)
    nonce = models.IntegerField(null=True)
    timestamp = models.FloatField(default=get_timestamp)

    def __str__(self):
        return str(self.id)

class VoteBackup(models.Model):
    """This model acts as backup; its objects shall never be tampered."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    vote = models.IntegerField(default=get_vote)
    timestamp = models.FloatField(default=get_timestamp)
    block_id = models.IntegerField(null=True)

    def __str__(self):
        return "{}|{}|{}".format(self.id, self.vote, self.timestamp)

simulation/views.py
import datetime, time, json, math
from random import randint
from uuid import uuid4
from Crypto.Hash import SHA3_256
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.conf import settings
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect

from .models import Vote, Block, VoteBackup
from .merkle.merkle_tool import MerkleTools

def generate(request):
    """Generate transactions and fill them with valid values."""
    number_of_transactions = settings.N_TRANSACTIONS
    number_of_tx_per_block = settings.N_TX_PER_BLOCK

    # Delete all data from previous demo.
    deleted_old_votes = Vote.objects.all().delete()[0]
    VoteBackup.objects.all().delete()
    print('\nDeleted {} data from previous simulation.\n'.format(deleted_old_votes))
    # Delete all blocks from previous demo.
    deleted_old_blocks = Block.objects.all().delete()[0]
    print("\nDeleted {} blocks from previous simulation.\n".format(deleted_old_blocks))
    
    # Generate transactions.
    time_start = time.time()
    block_no = 1
    for i in range(1, number_of_transactions + 1):
        # generate random, valid values
        v_id = str(uuid4())
        v_cand = _get_vote()
        v_timestamp = _get_timestamp()
        # directly fill the values and the block id for simulation purpose
        new_vote = Vote(id=v_id, vote=v_cand, timestamp=v_timestamp, block_id=block_no)
        new_backup_vote = VoteBackup(id=v_id, vote=v_cand, timestamp=v_timestamp, block_id=block_no)
        # "Broadcast" to two nodes
        new_vote.save()
        new_backup_vote.save()
        print("#{} new vote: {}".format(i, new_vote)) # for sanity
        if i % number_of_tx_per_block == 0:
            block_no += 1
    time_end = time.time()
    print('\nFinished in {} seconds.\n'.format(time_end - time_start))

    # View the generated transactions
    votes = Vote.objects.order_by('-timestamp')[:100] # only shows the last 100, if any
    context = {
        'votes': votes,
    }
    request.session['transactions_done'] = True
    return render(request, 'simulation/generate.html', context)

def seal(request):
    """Seal the transactions generated previously."""
    if request.session.get('transactions_done') is None:
        redirect('welcome:home')
    del request.session['transactions_done']

    # Puzzle requirement: '0' * (n leading zeros)
    puzzle, pcount = settings.PUZZLE, settings.PLENGTH

    # Seal transactions into blocks
    time_start = time.time()
    number_of_blocks = settings.N_BLOCKS
    prev_hash = '0' * 64
    for i in range(1, number_of_blocks + 1):
        block_transactions = Vote.objects.filter(block_id=i).order_by('timestamp')
        root = MerkleTools()
        root.add_leaf([str(tx) for tx in block_transactions], True)
        root.make_tree()
        merkle_h = root.get_merkle_root()
        
        # Try to seal the block and generate valid hash
        nonce = 0
        timestamp = datetime.datetime.now().timestamp()
        while True:
            enc = ("{}{}{}{}".format(prev_hash, merkle_h, nonce, timestamp)).encode('utf-8')
            h = SHA3_256.new(enc).hexdigest()
            if h[:pcount] == puzzle:
                break
            nonce += 1

        # Create the block
        block = Block(id=i, prev_h=prev_hash, merkle_h=merkle_h, h=h, nonce=nonce, timestamp=timestamp)
        block.save()
        print('\nBlock {} is mined\n'.format(i))
        # Set this hash as prev hash
        prev_hash = h

    time_end = time.time()
    print('\nSuccessfully created {} blocks.\n'.format(number_of_blocks))
    print('\nFinished in {} seconds.\n'.format(time_end - time_start))
    return redirect('simulation:blockchain')

def transactions(request):
    """See all transactions that have been contained in blocks."""
    vote_list = Vote.objects.all().order_by('timestamp')
    paginator = Paginator(vote_list, 100, orphans=20, allow_empty_first_page=True)

    page = request.GET.get('page')
    votes = paginator.get_page(page)

    hashes = [SHA3_256.new(str(v).encode('utf-8')).hexdigest() for v in votes]
    
    # This happens if you don't use foreign key
    block_hashes = []
    for i in range(0, len(votes)):
        try:
            b = Block.objects.get(id=votes[i].block_id)
            h = b.h
        except:
            h = 404
        block_hashes.append(h)
    
    # zip the three iters
    votes_pg = votes # for pagination
    votes = zip(votes, hashes, block_hashes)
    
    # Calculate the voting result of 3 cands, the ugly way
    result = []
    for i in range(0, 3):
        try:
            r = Vote.objects.filter(vote=i+1).count()
        except:
            r = 0
        result.append(r)

    context = {
        'votes': votes,
        'result': result,
        'votes_pg': votes_pg,
    }
    return render(request, 'simulation/transactions.html', context)

def blockchain(request):
    """See all mined blocks."""
    blocks = Block.objects.all().order_by('id')
    context = {
        'blocks': blocks,
    }
    return render(request, 'simulation/blockchain.html', context)

def verify(request):
    """Verify transactions in all blocks by re-calculating the merkle root."""
    # Basically, by just creating a session (message) var

    print('verifying data...')
    number_of_blocks = Block.objects.all().count()
    corrupt_block_list = ''
    for i in range(1, number_of_blocks + 1):
        # Select block #i
        b = Block.objects.get(id=i)
        
        # Select all transactions in block #i
        transactions = Vote.objects.filter(block_id=i).order_by('timestamp')

        # Verify them
        root = MerkleTools()
        root.add_leaf([str(tx) for tx in transactions], True)
        root.make_tree()
        merkle_h = root.get_merkle_root()
        
        if b.merkle_h == merkle_h:
            message = 'Block {} verified.'.format(i)
        else:
            message = 'Block {} is TAMPERED'.format(i)
            corrupt_block_list += ' {}'.format(i)
        print('{}'.format(message))
    if len(corrupt_block_list) > 0:
        messages.warning(request, 'The following blocks have corrupted transactions: {}.'.format(corrupt_block_list), extra_tags='bg-danger')
    else:
        messages.info(request, 'All transactions in blocks are intact.', extra_tags='bg-info')
    return redirect('simulation:blockchain')

def sync(request):
    """Restore transactions from honest node."""
    deleted_old_votes = Vote.objects.all().delete()[0]
    print('\nTrying to sync {} transactions with 1 node(s)...\n'.format(deleted_old_votes))
    bk_votes = VoteBackup.objects.all().order_by('timestamp')
    for bk_v in bk_votes:
        vote = Vote(id=bk_v.id, vote=bk_v.vote, timestamp=bk_v.timestamp, block_id=bk_v.block_id)
        vote.save()
    print('\nSync complete.\n')
    messages.info(request, 'All blocks have been synced successfully.')
    return redirect('simulation:blockchain')

def sync_block(request, block_id):
    """Restore transactions of a block from honest node."""
    b = Block.objects.get(id=block_id)
    print('\nSyncing transactions in block {}\n'.format(b.id))
    # Get all existing transactions in this block and delete them
    Vote.objects.filter(block_id=block_id).delete()
    # Then rewrite from backup node
    bak_votes = VoteBackup.objects.filter(block_id=block_id).order_by('timestamp')
    for bv in bak_votes:
        v = Vote(id=bv.id, vote=bv.vote, timestamp=bv.timestamp, block_id=bv.block_id)
        v.save()
    # Just in case, delete transactions without valid block
    block_count = Block.objects.all().count()
    Vote.objects.filter(block_id__gt=block_count).delete()
    Vote.objects.filter(block_id__lt=1).delete()
    print('\nSync complete\n')
    return redirect('simulation:block_detail', block_hash=b.h)

def block_detail(request, block_hash):
    """See the details of a block and its transactions."""
    # Select the block or 404
    block = get_object_or_404(Block, h=block_hash)
    confirmed_by = (Block.objects.all().count() - block.id) + 1
    # Select all corresponding transactions
    transaction_list = Vote.objects.filter(block_id=block.id).order_by('timestamp')
    paginator = Paginator(transaction_list, 100, orphans=20)

    page = request.GET.get('page')
    transactions = paginator.get_page(page)
    transactions_hashes = [SHA3_256.new(str(t).encode('utf-8')).hexdigest() for t in transactions]
    
    # Check the integrity of transactions
    root = MerkleTools()
    root.add_leaf([str(tx) for tx in transaction_list], True)
    root.make_tree()
    merkle_h = root.get_merkle_root()
    tampered = block.merkle_h != merkle_h
    
    transactions_pg = transactions # for pagination
    transactions = zip(transactions, transactions_hashes)
    
    # Get prev and next block id
    prev_block = Block.objects.filter(id=block.id - 1).first()
    next_block = Block.objects.filter(id=block.id + 1).first()

    context = {
        'bk': block,
        'confirmed_by': confirmed_by,
        'transactions': transactions,
        'tampered': tampered,
        'verified_merkle_h': merkle_h,
        'prev_block': prev_block,
        'next_block': next_block,
        'transactions_pg': transactions_pg,
    }

    return render(request, 'simulation/block.html', context)

# HELPER FUNCTIONS
def _get_vote():
    return randint(1, 3)

def _get_timestamp():
    return datetime.datetime.now().timestamp()

simulation/templates/simulation/block.html
{% extends 'base.html' %}
{% load static %}
{% load sim_filters %}
{% block title_bl %}Block #{{ bk.pk }}{% endblock %}

{% block body_bl %}
<div class="container">
    <h1 class="pb-1">Block #{{ bk.id }}</h1>
    <a class="btn btn-light btn-sm" href="{% url 'simulation:blockchain' %}" role="button">Back to blocks list</a>
    <a class="btn btn-light btn-sm" href="{% url 'welcome:home' %}" role="button">Back to homepage</a>
    <div class="mt-1" style="padding: 3%; border: 1px solid black;">
        <dl class="row">
            <dt class="col-sm-3">Previous hash</dt>
            <dd class="col-sm-9"><code>{{ bk.prev_h }}</code></dd>

            <dt class="col-sm-3">Merkle root hash</dt>
            <dd class="col-sm-9"><code>{{ bk.merkle_h }}</code></dd>

            <dt class="col-sm-3">Block hash</dt>
            <dd class="col-sm-9"><code>{{ bk.h }}</code></dd>

            <dt class="col-sm-3">Nonce</dt>
            <dd class="col-sm-9">{{ bk.nonce }}</dd>

            <dt class="col-sm-3">Timestamp</dt>
            <dd class="col-sm-9">{{ bk.timestamp|unix_to_date|date:"Y-m-d H:i:s" }} ({{ bk.timestamp|unix_to_date|timesince }} ago)</dd>

            <dt class="col-sm-3">Confirmations</dt>
            <dd class="col-sm-9">{{ confirmed_by }} confirmations</dd>
        </dl>
    </div>
    <div class="p-2" id="block-navigation">
        {% if prev_block %}
            <a class="btn btn-primary btn-sm" href="{% url 'simulation:block_detail' block_hash=prev_block.h %}" role="button">Previous block</a>
        {% endif %}
        {% if next_block %}
            <a class="btn btn-primary btn-sm" href="{% url 'simulation:block_detail' block_hash=next_block.h %}" role="button">Next block</a>
        {% endif %}
    </div>
    <div>
        <h2>Transactions</h2>
        <p>Re-calculated merkle root hash: <code>{{ verified_merkle_h }}</code></p>
        {% if tampered %}
        <div class="bg-danger text-white">
            <p>Transactions are tampered <a class="btn btn-primary btn-sm" href="{% url 'simulation:sync_block' block_id=bk.id %}" role="button">Sync with other nodes</a></p>
        </div>
        {% else %}
            <div class="bg-success text-white">
                <p>Transactions are not tampered</p>
            </div>
        {% endif %}

        <small>Showing page {{ transactions_pg.number }} of {{ transactions_pg.paginator.num_pages }}</small>
        <div class="pagination pb-2">
            <span class="step-links">
                {% if transactions_pg.has_previous %}
                    <a class="btn btn-light btn-sm" href="?page=1" role="button">&laquo; First</a>
                    <a class="btn btn-light btn-sm" href="?page={{ transactions_pg.previous_page_number }}" role="button">Previous</a>
                {% endif %}
                {% if transactions_pg.has_next %}
                    <a class="btn btn-light btn-sm" href="?page={{ transactions_pg.next_page_number }}" role="button">Next</a>
                    <a class="btn btn-light btn-sm" href="?page={{ transactions_pg.paginator.num_pages }}" role="button">Last &raquo;</a>
                {% endif %}
            </span>
        </div>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Voter ID</th>
                    <th scope="col">Cand</th>
                    <th scope="col">Timestamp</th>
                    <th scope="col">Hash</th>
                </tr>
            </thead>
            <tbody>
                {% for t, h in transactions %}
                <tr>
                    <td>{{ forloop.counter }}</th>
                    <td><code>{{ t.id }}</code></td>
                    <td>{{ t.vote }}</td>
                    <td>{{ t.timestamp|unix_to_date|date:"Y-m-d H:i:s" }}</td>
                    <td title="{{ h }}"><code>{{ h|truncatechars:32 }}</code></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

simulation/templates/simulation/blockchain.html
{% extends 'base.html' %}
{% load sim_filters %}
{% block title_bl %}Blocks{% endblock %}

{% block body_bl %}
<div class="container">
    <h1>List of blocks</h1>
    <a class="btn btn-light btn-sm" href="{% url 'simulation:transactions' %}" role="button">See all transactions</a>
    <a class="btn btn-light btn-sm" href="{% url 'welcome:home' %}" role="button">Back to homepage</a>
    {% if messages %}
        {% for message in messages %}
            <div class="{{ message.extra_tags }} text-white">
                <p>{{ message }}</p>
            </div>
        {% endfor %}
    {% endif %}
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Previous Hash</th>
                <th scope="col">Block Hash</th>
                <th scope="col">Merkle Root Hash</th>
                <th scope="col">Nonce</th>
                <th scope="col">Timestamp</th>
            </tr>
        </thead>
        <tbody>
            {% for block in blocks %}
            <tr>
                <td><a href="{% url 'simulation:block_detail' block_hash=block.h %}">{{ block.id }}</a></th>
                <td title="{{ block.prev_h }}"><code>{{ block.prev_h|truncatechars:30 }}</code></td>
                <td title="{{ block.h }}"><code>{{ block.h|truncatechars:30 }}</code></td>
                <td title="{{ block.merkle_h }}"><code>{{ block.merkle_h|truncatechars:30 }}</code></td>
                <td>{{ block.nonce }}</td>
                <td>{{ block.timestamp|unix_to_date|date:"Y-m-d H:i:s" }}</td>
            </tr>
            {% empty %}
                <p>No record.</p>
            {% endfor %}
        </tbody>
    </table>
    <a class="btn btn-outline-primary btn-block" href="{% url 'simulation:verify' %}" role="button" title="Verify all transactions in each block">Verify</a>
    <a class="btn btn-outline-primary btn-block" href="{% url 'simulation:sync' %}" role="button" title="Sync data with virtual nodes">Sync</a>
</div>
{% endblock %}

simulation/templates/simulation/generate.html
{% extends 'base.html' %}
{% block title_bl %}Transactions{% endblock %}

{% block body_bl %}
<div class="container">
    <h1>List of unconfirmed votes</h1>
    <p>Showing last 100 transactions (or all if &lt;=100)</p>
    
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Voter ID</th>
                <th scope="col">Vote</th>
                <th scope="col">Timestamp</th>
            </tr>
        </thead>
        <tbody>
            {% for ballot in votes %}
            <tr>
                <td><code>{{ ballot.id }}</code></th>
                <td>{{ ballot.vote }}</td>
                <td>{{ ballot.timestamp }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
    <a class="btn btn-primary btn-block" href="{% url 'simulation:seal' %}" role="button">Mine into blocks</a>
</div>
{% endblock %}

simulation/templates/simulation/transactions.html
{% extends 'base.html' %}
{% load sim_filters %}
{% block title_bl %}Transactions{% endblock %}

{% block body_bl %}
<div class="container">
    <h1>List of confirmed votes</h1>
    <a class="btn btn-light btn-sm" href="{% url 'simulation:blockchain' %}" role="button">See all blocks</a>
    <a class="btn btn-light btn-sm" href="{% url 'welcome:home' %}" role="button">Back to homepage</a>
    <div style="margin:1%; padding:1%; border:1px solid black;">
        {% for r in result %}
            Candidate #{{ forloop.counter }}: {{ r }} votes<br>
        {% endfor %}
    </div>

    <small>Showing page {{ votes_pg.number }} of {{ votes_pg.paginator.num_pages }}</small>
    <div class="pagination pb-2">
        <span class="step-links">
            {% if votes_pg.has_previous %}
                <a class="btn btn-light btn-sm" href="?page=1" role="button">&laquo; First</a>
                <a class="btn btn-light btn-sm" href="?page={{ votes_pg.previous_page_number }}" role="button">Previous</a>
            {% endif %}
            {% if votes_pg.has_next %}
                <a class="btn btn-light btn-sm" href="?page={{ votes_pg.next_page_number }}" role="button">Next</a>
                <a class="btn btn-light btn-sm" href="?page={{ votes_pg.paginator.num_pages }}" role="button">Last &raquo;</a>
            {% endif %}
        </span>
    </div>

    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Voter ID</th>
                <th scope="col">Vote</th>
                <th scope="col">Timestamp</th>
                <th scope="col">Hash</th>
                <th scope="col">Block</th>
            </tr>
        </thead>
        <tbody>
            {% for ballot, h, bh in votes %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><code>{{ ballot.id }}</code></th>
                <td>{{ ballot.vote }}</td>
                <td>{{ ballot.timestamp|unix_to_date|date:"Y-m-d H:i:s" }}</td>
                <td title="{{ h }}"><code>{{ h|truncatechars:20 }}</code></td>
                <td><a class="btn btn-light btn-sm" href="{% url 'simulation:block_detail' block_hash=bh %}" role="button">go to block</a></td>
            </tr>
            {% empty %}
                <p>No record.</p>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}